In [1]:
import pandas as pd
import numpy as np
from tempfile import TemporaryFile

In [2]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [3]:
arr1 = np.arange(1, 6)
arr2 = np.arange(1, 6)

In [4]:
sales = np.random.randint(low=1, high=100, size=20)
print(sales)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [5]:
sales != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [6]:
(sales >= 50) & (sales <= 70)

array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False])

In [7]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
two_conditions = [x>5, x< 15]
print(two_conditions)

[array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]]), array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])]


In [10]:
[x, x**2]

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])]

In [13]:
r1 = np.arange(1, 11)
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
print(sales)
sales_gt_50 = sales > 50
print(f'sales greater than 50 filter : {sales_gt_50}')
np.select([sales_gt_50], [sales], 0)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
sales greater than 50 filter : [False False  True  True  True False  True False False  True  True  True
  True False  True  True False  True False  True]


array([ 0,  0, 65, 68, 68,  0, 84,  0,  0, 88, 71, 89, 89,  0, 59, 66,  0,
       88,  0, 89])

In [88]:
condition = sales > 50
np.select([sales > 50], [sales], np.nan)

array([71., 89., 89., nan, 59., 66., nan, 88., nan, 89., 82., nan, nan,
       78., 73., nan, nan, 81., 70., 80.])

In [25]:
np.greater(sales, 50)

array([False, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True])

In [105]:
np.select([sales > 50], [sales], default=np.nan)

array([71., 89., 89., nan, 59., 66., nan, 88., nan, 89., 82., nan, nan,
       78., 73., nan, nan, 81., 70., 80.])

In [107]:
np.select([sales > 50], [sales], default=0).nonzero()

(array([ 0,  1,  2,  4,  5,  7,  9, 10, 13, 14, 17, 18, 19]),)

In [123]:
r1 = np.arange(1, 11, 1)
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
filter1 = np.select([r1 > 5], [r1], default=0)

filter1

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [129]:
idx = np.select([r1 > 5], [r1], default=0).nonzero()
idx

(array([5, 6, 7, 8, 9]),)

In [133]:
vi_x = np.where(filter1 > 0)
vi_x

(array([5, 6, 7, 8, 9]),)

In [102]:
r1[vi_x]

array([16, 17, 18, 19, 20])

In [134]:
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
r1[r1 > 5]

array([ 6,  7,  8,  9, 10])

In [136]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [137]:
np.take(r1, idx)

array([[ 6,  7,  8,  9, 10]])

In [138]:
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
np.where(r1 > 5, r1, np.nan)

array([nan, nan, nan, nan, nan,  6.,  7.,  8.,  9., 10.])