In [2]:
import pandas as pd
import numpy as np

In [25]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [21]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [33]:
sales = np.random.randint(1, 100, 10)
print(sales)

[10 58 33 32 75 24 36 76 56 29]


In [34]:
sales.fill(0)

In [36]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,3])

In [37]:
np.equal(a1, a2)

array([ True,  True,  True])

In [38]:

np.array_equal(a1, a2)

True

In [39]:
np.not_equal(a1, a2)

array([False, False, False])

In [40]:
np.greater(a1, a2)

array([False, False, False])

In [41]:
np.logical_and(a1, a2)

array([ True,  True,  True])

In [45]:
np.logical_not(a1, a2)

array([0, 0, 0])