In [5]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [7]:
arr1 = np.arange(1, 6)
arr2 = np.arange(1, 6)

In [9]:
sales = np.random.randint(low=1, high=100, size=20)
print(sales)

[71 89 89 13 59 66 40 88 47 89 82 38 26 78 73 10 21 81 70 80]


In [10]:
sales != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
(sales >= 50) & (sales <= 70)

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False])

In [14]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
[x>5, x< 15]

[array([[False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False]])]

In [17]:
[x, x**2]

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])]

In [25]:
r1 = np.arange(1, 11)
np.select()

In [22]:
x.shape

(4, 5)

In [29]:
condition = sales > 50
np.select([sales > 50], [sales ], np.nan)

array([71., 89., 89., nan, 59., 66., nan, 88., nan, 89., 82., nan, nan,
       78., 73., nan, nan, 81., 70., 80.])

In [32]:
np.greater(sales, 50)

array([ True,  True,  True, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True])

In [33]:
from tempfile import TemporaryFile

In [34]:
with TemporaryFile('w+t') as f:
    f.write('Hello World\n')
    f.seek(0)
    data = f.read()
    print(data)

Hello World



In [35]:
import os

In [36]:
os.O_EXCL

2048

In [37]:
os.stat('/')

os.stat_result(st_mode=16877, st_ino=2, st_dev=16777232, st_nlink=20, st_uid=0, st_gid=0, st_size=640, st_atime=1709179520, st_mtime=1709179520, st_ctime=1709179520)

In [38]:
os.name

'posix'

In [39]:
os.uname()

posix.uname_result(sysname='Darwin', nodename='boula_mac', release='23.4.0', version='Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103', machine='arm64')

In [40]:
import platform

In [43]:
platform.system(), platform.release(), platform.version()

('Darwin',
 '23.4.0',
 'Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103')