In [67]:
import pandas as pd
import numpy as np
from tempfile import TemporaryFile

In [6]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [7]:
arr1 = np.arange(1, 6)
arr2 = np.arange(1, 6)

In [9]:
sales = np.random.randint(low=1, high=100, size=20)
print(sales)

[71 89 89 13 59 66 40 88 47 89 82 38 26 78 73 10 21 81 70 80]


In [10]:
sales != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
(sales >= 50) & (sales <= 70)

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False])

In [14]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
[x>5, x< 15]

[array([[False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False]])]

In [17]:
[x, x**2]

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])]

In [86]:
r1 = np.arange(1, 11)

In [87]:
x.shape

(4, 5)

In [88]:
condition = sales > 50
np.select([sales > 50], [sales], np.nan)

array([71., 89., 89., nan, 59., 66., nan, 88., nan, 89., 82., nan, nan,
       78., 73., nan, nan, 81., 70., 80.])

In [89]:
np.greater(sales, 50)

array([ True,  True,  True, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True])

In [90]:
r1[r1 > 5]

array([ 6,  7,  8,  9, 10])

In [105]:
np.select([sales > 50], [sales], default=np.nan)

array([71., 89., 89., nan, 59., 66., nan, 88., nan, 89., 82., nan, nan,
       78., 73., nan, nan, 81., 70., 80.])

In [107]:
np.select([sales > 50], [sales], default=0).nonzero()

(array([ 0,  1,  2,  4,  5,  7,  9, 10, 13, 14, 17, 18, 19]),)

In [123]:
r1 = np.arange(1, 11, 1)
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
filter1 = np.select([r1 > 5], [r1], default=0)

filter1

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [129]:
idx = np.select([r1 > 5], [r1], default=0).nonzero()
idx

(array([5, 6, 7, 8, 9]),)

In [133]:
vi_x = np.where(filter1 > 0)
vi_x

(array([5, 6, 7, 8, 9]),)

In [102]:
r1[vi_x]

array([16, 17, 18, 19, 20])

In [134]:
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
r1[r1 > 5]

array([ 6,  7,  8,  9, 10])

In [136]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [137]:
np.take(r1, idx)

array([[ 6,  7,  8,  9, 10]])

In [138]:
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
np.where(r1 > 5, r1, np.nan)

array([nan, nan, nan, nan, nan,  6.,  7.,  8.,  9., 10.])