In [2]:
import pandas as pd
import numpy as np

In [8]:
np.random.seed(0)

In [11]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1 + 5

array([ 6,  7,  8,  9, 10, 11])

In [12]:
np.add(arr1, 5)

array([ 6,  7,  8,  9, 10, 11])

In [13]:
np.divide(arr1, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [14]:
np.multiply(arr1, 2)

array([ 2,  4,  6,  8, 10, 12])

In [20]:
np.reciprocal([1,2,3,4,5,6], dtype=float)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [19]:
np.reciprocal([1,2,4,8], dtype=float)

array([1.   , 0.5  , 0.25 , 0.125])