In [2]:
import pandas as pd
import numpy as np

In [8]:
np.random.seed(0)

In [11]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1 + 5

array([ 6,  7,  8,  9, 10, 11])

In [12]:
np.add(arr1, 5)

array([ 6,  7,  8,  9, 10, 11])

In [13]:
np.divide(arr1, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])