In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import pandas as pd
import numpy as np
from tempfile import TemporaryFile

In [5]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [6]:
sales = np.random.randint(low=1, high=100, size=10)
print(f"sales {sales}")


sales [45 48 65 68 68 10 84 22 37 88]


In [7]:
[sales > 50, sales]

[array([False, False,  True,  True,  True, False,  True, False, False,
         True]),
 array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])]

In [15]:
high_sales = np.select([sales > 50], [sales], np.nan)
low_sales  = np.select([sales < 50], [sales], np.nan)
print(f"high_sales {high_sales}")
print(f"low_sales {low_sales}")

high_sales [nan nan 65. 68. 68. nan 84. nan nan 88.]
low_sales [45. 48. nan nan nan 10. nan 22. 37. nan]


In [9]:
np.extract(sales > 50, sales)

array([65, 68, 68, 84, 88])

In [23]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
np.extract([arr1 > 3] , arr1)

array([4, 5, 6])