In [5]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [7]:
arr1 = np.arange(1, 6)
arr2 = np.arange(1, 6)

In [9]:
sales = np.random.randint(low=1, high=100, size=20)
print(sales)

[71 89 89 13 59 66 40 88 47 89 82 38 26 78 73 10 21 81 70 80]


In [10]:
sales != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
(sales >= 50) & (sales <= 70)

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False])

In [14]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
[x>5, x< 15]

[array([[False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False]])]

In [17]:
[x, x**2]

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])]