In [2]:
import pandas as pd
import numpy as np

In [25]:
np.random.seed(0)
rng= np.random.default_rng(123)

In [21]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [65]:
sales = np.random.randint(1, 100, 10)
print(sales)

[43 59 32  2 66 42 58 36 12 47]


In [66]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,3])

In [67]:
np.equal(a1, a2)

array([ True,  True,  True])

In [72]:
(sales > 50) & (sales < 70)

array([False,  True, False, False,  True, False,  True, False, False,
       False])

In [73]:
f1 = np.logical_and(sales > 50, sales < 70)
f1

array([False,  True, False, False,  True, False,  True, False, False,
       False])

In [75]:
np.count_nonzero(f1)

3

In [77]:
np.unique(f1, return_counts=True)

(array([False,  True]), array([7, 3]))