In [134]:
import numpy as np
import pandas as pd

### one dimension Series

In [135]:
s1 = pd.Series(np.arange(5), name='Series1', index=list('row'+str(x) for x in range(5)))
s1

row0    0
row1    1
row2    2
row3    3
row4    4
Name: Series1, dtype: int64

#####  Series Attributes

In [136]:
print('| shape:', s1.size, '|dimension:', s1.ndim,'| shape:', s1.shape, '| dtype:', s1.dtype, '| name:', s1.name,
     '| is empty:', s1.empty, '| has nans:', s1.hasnans)

| shape: 5 |dimension: 1 | shape: (5,) | dtype: int64 | name: Series1 | is empty: False | has nans: False


In [137]:
# change index passing list comprehension
s1.index=list('row'+str(x) for x in range(s1.size))
s1.index

Index(['row0', 'row1', 'row2', 'row3', 'row4'], dtype='object')

##### Iterate overs index & value

In [138]:
for index, value in s1.items():
    print(f"Index name \t: {index}, \tValue : {value}")
    

Index name 	: row0, 	Value : 0
Index name 	: row1, 	Value : 1
Index name 	: row2, 	Value : 2
Index name 	: row3, 	Value : 3
Index name 	: row4, 	Value : 4


#####  Sort a Series in ascending or descending order

In [139]:
s1.sort_values(ascending=False)

row4    4
row3    3
row2    2
row1    1
row0    0
Name: Series1, dtype: int64

In [140]:
s2=pd.Series([6,7,8,9,10,11], name='Series2')
s2

0     6
1     7
2     8
3     9
4    10
5    11
Name: Series2, dtype: int64

##### pandas.Series.append¶


In [141]:
s3=s1.append(s2,ignore_index=True, verify_integrity=False)

In [142]:
s3

0      0
1      1
2      2
3      3
4      4
5      6
6      7
7      8
8      9
9     10
10    11
dtype: int64

In [143]:
s3.reindex() # pandas.Series.reindex¶

0      0
1      1
2      2
3      3
4      4
5      6
6      7
7      8
8      9
9     10
10    11
dtype: int64

In [144]:
s1.empty

False

In [145]:
s3.values

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [146]:
s3[11]=99

In [147]:
s3.values

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 99])

In [148]:
s3.pop(11) # Return item and drops from series. Raise KeyError if not found.


99

In [149]:
s3.values

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [10]:
s1[[0,3,6]]

row1    1
row4    4
row7    7
dtype: int64

In [11]:
s1[0:9:2]

row1    1
row3    3
row5    5
row7    7
row9    9
dtype: int64

In [12]:
s1['row2']

2

In [13]:
s1[9]=0

In [14]:
s1

row1     1
row2     2
row3     3
row4     4
row5     5
row6     6
row7     7
row8     8
row9     9
row10    0
dtype: int64

In [15]:
s1[[0,9]]=99

In [16]:
s1

row1     99
row2      2
row3      3
row4      4
row5      5
row6      6
row7      7
row8      8
row9      9
row10    99
dtype: int64

In [150]:
s1.head()

row0    0
row1    1
row2    2
row3    3
row4    4
Name: Series1, dtype: int64