In [1]:
import numpy as np

In [2]:
a1 = np.array(range(5))
a1

array([0, 1, 2, 3, 4])

In [3]:
print("ndim  : ", a1.ndim)
print("shape : ", a1.shape)
print("size  : ", a1.size)
print("dtype : ", a1.dtype )

ndim  :  1
shape :  (5,)
size  :  5
dtype :  int64


In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [5]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.exp(2)

7.38905609893065

In [9]:
2**2.71

6.543216468462249

In [10]:
2**2.71828

6.580877650466003

#### Random Number Generator

In [11]:
rng = np.random.default_rng(123)

In [16]:
rng.random(10)

array([0.07148681, 0.58323841, 0.2379064 , 0.76496365, 0.17363164,
       0.31274226, 0.01447448, 0.03255192, 0.49670184, 0.46831253])