In [202]:
import numpy as np

In [203]:
def nd_info(arr: np.array):
    print("ndim        : ", arr.ndim)
    print("shape       : ", arr.shape)
    print("size        : ", arr.size)
    print("dtype       : ", arr.dtype )
    print("object Type : ", type(arr))

### [Link to numpy basics types](https://numpy.org/devdocs/user/basics.types.html)

In [204]:
a1: np.array = np.array(range(5))
print(a1)

[0 1 2 3 4]


### [Numpy Data types](https://numpy.org/devdocs/user/basics.types.html)

In [205]:
print("ndim        : ", a1.ndim)
print("shape       : ", a1.shape)
print("size        : ", a1.size)
print("dtype       : ", a1.dtype )
print("object Type : ", type(a1))

ndim        :  1
shape       :  (5,)
size        :  5
dtype       :  int64
object Type :  <class 'numpy.ndarray'>


In [206]:
print(a1)

[0 1 2 3 4]


In [207]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [208]:
nd_info(a2)

ndim        :  2
shape       :  (3, 4)
size        :  12
dtype       :  int64
object Type :  <class 'numpy.ndarray'>


In [209]:
np.exp(2)

7.38905609893065

In [210]:
2**2.71

6.543216468462249

In [211]:
2**2.71828

6.580877650466003

# Array Creation

#### .ones Method

In [212]:
ones = np.ones(10, dtype=np.int8)
print(ones)

[1 1 1 1 1 1 1 1 1 1]


In [213]:
type(ones[0])

numpy.int8

In [160]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### .zeros Method

In [161]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### .arange Method

In [162]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
start=0
end=20
step=2
np.arange(start, end, step)
# start inclusive end exclusive

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### .linspace Method

In [169]:
linspace = np.linspace(1, 10, 20)
print(linspace)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [170]:
# calculating the range in numpy
random_numbers = np.random.randint(1, 100, 10)
random_numbers_range = np.max(random_numbers) - np.min(random_numbers)
print("Random Numbers:", random_numbers)
print("Range:", random_numbers_range)

Random Numbers: [97 94 11 12 30 85  9 79 60 65]
Range: 88


In [171]:
range_of_20 = np.arange(20).reshape(4,5)
range_of_20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### .full Method
Return a new array of given shape and type, filled with `fill_value`.

In [172]:
np.full((3,4), 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [173]:
np.full((3,3), [3,2,1])

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])

#### .empty Method
Return a new array of given shape and type, without initializing entries.

In [174]:
np.empty((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [175]:
np.array([range(i, i+4) for i in [1,2,3,4]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [176]:
np.array([range(i, i + 5) for i in range(1,6)])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

# Structured arrays

In [177]:
data = np.array([('Alice', 25, 62.5, True),
                ('Bob', 32, 70.2, False),
                ('Charlie', 28, 68.7, True)],
                dtype=[('name', 'U10'), ('age', int), ('weight', float), ('is_student', bool)])
data

array([('Alice', 25, 62.5,  True), ('Bob', 32, 70.2, False),
       ('Charlie', 28, 68.7,  True)],
      dtype=[('name', '<U10'), ('age', '<i8'), ('weight', '<f8'), ('is_student', '?')])

# Random Number Generator

In [178]:
rng = np.random.default_rng(seed=42)

#### rng.integers Method
Return random integers from the "discrete uniform" distribution

In [179]:
rng.integers(1,10,20)

array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1, 5, 9, 7, 7, 7, 8, 5, 2, 8, 5])

In [180]:
x1 = rng.integers(1,10,5)
np.sum(x1)

28

In [121]:
rng.integers(2, size=10)

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1])

#### rng.random Method   
return continuous uniform" distribution

In a continuous uniform distribution, all values within the specified interval have an equal probability of being generated.
The interval [0, 1) means that the generated numbers will be greater than or equal to 0 and less than 1.

In [122]:
rand_nums =  rng.random(10) * 10
rand_nums

array([8.27631172, 6.31664399, 7.5808774 , 3.54525968, 9.70698024,
       8.93121121, 7.78383497, 1.94638708, 4.66721004, 0.43803766])

In [123]:
np.sort(rand_nums)

array([0.43803766, 1.94638708, 3.54525968, 4.66721004, 6.31664399,
       7.5808774 , 7.78383497, 8.27631172, 8.93121121, 9.70698024])

In [124]:
rng.integers(1, 10, size=5, endpoint=True )

array([1, 6, 2, 8, 7])

#### rng.normal Method

normal(mean, std_dev, size)
Draw random samples from a normal (Gaussian) distribution.

In [125]:
mean = 5
std = 2
sample_size_1 = 7
rng.normal(mean, std, sample_size_1)
# normal(loc=0.0, scale=1.0, size=None)

array([9.2832952 , 4.18716997, 3.97551454, 3.37245454, 6.23195885,
       7.25794459, 4.77210508])

In [126]:
rng.normal(2, 2, 10)

array([0.31968705, 0.35103757, 3.30118558, 3.48650834, 3.08630854,
       0.66898059, 2.46432265, 2.23337162, 2.43737719, 3.74285756])

In [127]:
x = rng.integers(1,10,5)
x

array([6, 2, 8, 2, 8])

In [128]:
rng.choice(np.arange(100), 5, replace=True)

array([ 0, 79, 78, 78, 66])

# Filtering Array

#### Boolean Indexing 'filtering'

In [55]:
rnd = np.random.default_rng(321)

In [56]:
price_list = ( rng.random(20) * 100 ).round(2)
price_list

array([61.94,  1.94, 27.2 , 83.31, 12.48, 12.62,  7.63, 20.98, 71.06,
       46.04, 60.89, 78.75, 54.73, 33.43, 39.31, 43.78, 97.04,  1.8 ,
       76.05, 17.63])

In [57]:
price_list > 5

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True])

In [58]:
price_list != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [59]:
price_list[price_list > 50]

array([61.94, 83.31, 71.06, 60.89, 78.75, 54.73, 97.04, 76.05])

In [60]:
price_list[price_list < 50]

array([ 1.94, 27.2 , 12.48, 12.62,  7.63, 20.98, 46.04, 33.43, 39.31,
       43.78,  1.8 , 17.63])

In [61]:
price_list <= 30

array([False,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True])

In [62]:
least_30_products = price_list <= 30

price_list[least_30_products]

array([ 1.94, 27.2 , 12.48, 12.62,  7.63, 20.98,  1.8 , 17.63])

In [64]:
price_list >= 70

array([False, False, False,  True, False, False, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
        True, False])

In [65]:
greatest_30_products = price_list >= 70

price_list[greatest_30_products]

array([83.31, 71.06, 78.75, 97.04, 76.05])

In [67]:
filtered_array = price_list[(price_list <= 30) | (price_list >= 70)]

np.sort(filtered_array)

array([ 1.8 ,  1.94,  7.63, 12.48, 12.62, 17.63, 20.98, 27.2 , 71.06,
       76.05, 78.75, 83.31, 97.04])

In [132]:
products = np.array(["Apple", "Banana", "Orange", "Mango", "Grapes",
              "Strawberry", "Watermelon", "Pineapple", "Kiwi", "Peach"])

prices = rng.uniform(1.00, 100.00, size=10).round(2)

In [133]:
for product, price in zip(products, prices):
    print([product, price])

['Apple', 15.05]
['Banana', 40.85]
['Orange', 55.21]
['Mango', 11.94]
['Grapes', 31.85]
['Strawberry', 86.64]
['Watermelon', 96.78]
['Pineapple', 37.26]
['Kiwi', 93.61]
['Peach', 19.84]


In [134]:
products_less_than_50 = products[ prices < 50 ]
products_less_than_50

array(['Apple', 'Banana', 'Mango', 'Grapes', 'Pineapple', 'Peach'],
      dtype='<U10')

#### ndarray.all Method
Returns True if all elements evaluate to True.

In [137]:
a1 = np.arange(10)
print(a1)
print(a1.all()) # false
print('the first element in the array is evaluated to false')

[0 1 2 3 4 5 6 7 8 9]
False
the first element in the array is evaluated to false


In [151]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"numbers : {numbers}")
value = 33
print(f"match value: {value}")
booleans = np.isin(numbers, value)
print("np.isin Method returns a boolean array of the same shape")
print(booleans)
print()

if np.all(np.isin(numbers, value)):
    print("{value} is present in the array".format(value=value))
else:
    print("{value} is not present in the array".format(value=value))


numbers : [ 1  2  3  4  5  6  7  8  9 10]
match value: 33
np.isin Method returns a boolean array of the same shape
[False False False False False False False False False False]

33 is not present in the array


In [152]:
# get index of not matching condition
falsy_values_at_index = a1[np.logical_not(a1)]
falsy_values_at_index

array([0])

In [153]:
a4x5 = np.arange(20).reshape(4,5)
a4x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
a4x5 % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [155]:
# range_of_20_even =
a4x5[a4x5 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [156]:
np.where(a4x5 % 2 == 0, "even", "odd")

array([['even', 'odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even', 'odd']], dtype='<U4')

# Array Manipulation

In [160]:
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [162]:
ones.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [164]:
ones.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [187]:
arr_3x3 = np.arange(9).reshape(3,3)
arr_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [189]:
new_row = np.array([9, 10, 11])

# Append the new values as a new row
np.append(arr_3x3, [new_row], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [205]:
arr_3x3.shape

(3, 3)

In [206]:
new_col = np.array([9,10,11])
new_col

array([ 9, 10, 11])

#### np.transpose([new_col]) is used to reshape the new_values array to match the shape of the arr_3x3 array before appending it as a new column.

In [207]:
print(arr_3x3.shape)

(3, 3)


##### 
By using np.transpose([new_col]), we create a new array where the new_values array is enclosed in square brackets [], which effectively adds an extra dimension to the array. The np.transpose function is then applied to transpose the array, swapping the dimensions. This reshaping operation changes the shape of new_values from (3,) to (1, 3) or (3, 1) based on the transposition.

The transposed array np.transpose([new_col]) can now be appended as a new column to arr_3x3 using np.append with the axis option set to 1

In [209]:
np.transpose([new_col])

array([[ 9],
       [10],
       [11]])

In [210]:
print( np.transpose([new_col]).shape )

(3, 1)


In [211]:
arr_appended_col = np.append(arr_3x3, np.transpose([new_values]), axis=1)
np.append(arr_3x3, np.transpose([new_col]), axis=1)

array([[ 0,  1,  2,  9],
       [ 3,  4,  5, 10],
       [ 6,  7,  8, 11]])

In [213]:
np.transpose([[1,2,3]])

array([[1],
       [2],
       [3]])

# Aggregate Functions

In [53]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
print(arr.sum())  # Array-wise sum

66


In [55]:
print(arr.min())  # Array-wise minimum value

0


In [56]:
print(arr.max(axis=0))  # Maximum value of an array row

[ 8  9 10 11]


In [57]:
print(arr.max(axis=1))  # Maximum value of an array col

[ 3  7 11]


#### Returns the indices of the maximum values along an axis.

In [58]:
np.argmax(arr)

11

#### Returns the indices of the minimum values along an axis.

In [59]:
np.argmin(arr)

0

In [60]:
print(arr.mean())  # Mean

5.5


In [61]:
print(np.median(arr))  # Median

5.5


#### Return the cumulative sum of the elements along the given axis.

In [62]:
print(arr.cumsum(axis=1))  # Cumulative sum of the elements

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [63]:
print(np.corrcoef(arr))  # Correlation coefficient

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [64]:
print(np.std(arr))  # Standard deviation

3.452052529534663


# Array Mathematics

In [65]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1.5, 2, 3],
              [7, 8, 9]])


In [66]:
g = a - b  # Subtraction
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [67]:
np.subtract(a, b)  # Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [68]:
addition = b + a  # Addition
print(addition)

[[ 2.5  4.   6. ]
 [11.  13.  15. ]]


In [69]:
np.add(b, a)  # Addition

array([[ 2.5,  4. ,  6. ],
       [11. , 13. , 15. ]])

##### division

In [70]:
division = a / b  # Division
print(division)

[[0.66666667 1.         1.        ]
 [0.57142857 0.625      0.66666667]]


In [71]:
np.divide(a, b)  # Division

array([[0.66666667, 1.        , 1.        ],
       [0.57142857, 0.625     , 0.66666667]])

In [72]:
multiplication = a * b  # Multiplication
print(multiplication)

[[ 1.5  4.   9. ]
 [28.  40.  54. ]]


In [73]:
np.multiply(a, b)  # Multiplication

array([[ 1.5,  4. ,  9. ],
       [28. , 40. , 54. ]])

In [74]:
exponentiation = np.exp(b)  # Exponentiation
print(exponentiation)

[[4.48168907e+00 7.38905610e+00 2.00855369e+01]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [75]:
square_root = np.sqrt(b)  # Square root
print(square_root)

[[1.22474487 1.41421356 1.73205081]
 [2.64575131 2.82842712 3.        ]]


In [76]:
sines = np.sin(a)  # Print sines of an array
print(sines)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [77]:
cosines = np.cos(b)  # Element-wise cosine
print(cosines)

[[ 0.0707372  -0.41614684 -0.9899925 ]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [78]:
logarithm = np.log(a)  # Element-wise natural logarithm
print(logarithm)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [79]:
e = np.array([[1, 1],
              [1, 1]])
f = np.array([[1, 1],
              [1, 1]])
dot_product = np.dot(e, f)  # Dot product
print(dot_product)

[[2 2]
 [2 2]]


# Indexing & Slicing Arrays

In [136]:
countries = np.array([
    ['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
    ['France', 'Germany', 'Hungary', 'India', 'Japan'],
    ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
    ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
    ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']
])
countries

array([['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
       ['France', 'Germany', 'Hungary', 'India', 'Japan'],
       ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
       ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
       ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']], dtype='<U13')

In [81]:
countries[3,-1]

'United States'

In [82]:
countries[:, 3] # all rows - column 3

array(['Denmark', 'India', 'Oman', 'Thailand', 'Yemen'], dtype='<U13')

In [144]:
countries[:, 1:3] # all rows - second and third columns - last column excluded

array([['Brazil', 'Canada'],
       ['Germany', 'Hungary'],
       ['Mexico', 'Netherlands'],
       ['Russia', 'Spain'],
       ['Wales', 'Xenobia']], dtype='<U13')

In [145]:
countries[:2, 3:] # first 2 rows and columns 4 to the end

array([['Denmark', 'Egypt'],
       ['India', 'Japan']], dtype='<U13')

In [146]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
isEven= lambda x: x%2 == 0
isOdd = lambda n: n%2 != 0

In [148]:
result =[]
for x in range(n1.size):
    if isEven(x):
        result.append(x)

result

[0, 2, 4, 6, 8]

In [88]:
n1 = rng.integers(1, 100, 10)
n1

array([40, 12, 98, 20, 88, 67, 59,  7, 77, 60])

In [89]:
n1 > 50 # return numpy.ndarray

array([False, False,  True, False,  True,  True,  True, False,  True,
        True])

In [90]:
n1 % 2 == 0

array([ True,  True,  True,  True,  True, False, False, False, False,
        True])

In [91]:
mask_1 = np.in1d(n1, 83)
n1[mask_1]

array([], dtype=int64)

In [92]:
ar1 = np.arange(1, 21)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
ar1[ar1 %2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [94]:
even_odd = np.array(['even', 'odd'] * 5)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [95]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [96]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
np.where(ar1 %2==0, ar1/2, ar1/3)

array([ 0.33333333,  1.        ,  1.        ,  2.        ,  1.66666667,
        3.        ,  2.33333333,  4.        ,  3.        ,  5.        ,
        3.66666667,  6.        ,  4.33333333,  7.        ,  5.        ,
        8.        ,  5.66666667,  9.        ,  6.33333333, 10.        ])

In [98]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
ar2 = np.arange(19,-1, -1)
ar2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [100]:
ar1 + ar2

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20])

In [101]:
ar1.sort()

In [102]:
arr = np.array(['apple', 10, [1, 2, 3], {'key': 'value'}], dtype=object)

print(arr)
print(arr.dtype)

['apple' 10 list([1, 2, 3]) {'key': 'value'}]
object


In [103]:
unorder_arr = np.random.randint(1, 101, 10)
unorder_arr

array([79, 86, 43, 13, 91, 43, 79, 56, 96, 91])

In [104]:
unorder_arr.sort()
unorder_arr

array([13, 43, 43, 56, 79, 79, 86, 91, 91, 96])

In [105]:
desc_arr = np.flip(unorder_arr)
desc_arr

array([96, 91, 91, 86, 79, 79, 56, 43, 43, 13])

In [106]:
l1=[1,2,3,4,5]
l2=[6,7,8]

In [107]:
list(zip(l1,l2))

[(1, 6), (2, 7), (3, 8)]

### Vectorization

In [108]:
list1 = rng.integers(1, 1001, 1000)
list2 = rng.integers(1, 1001, 1000)

In [109]:
def for_loop_mutiply_arrays(array1, array2):
    product_array = []
    for n1, n2 in zip(array1, array2):
        product_array.append(n1 * n2)
    return product_array


In [110]:
def multiply_arrays(array1, array2):
    return array1 * array2

In [111]:
%%timeit -r 5 -n 10000
for_loop_mutiply_arrays(list1, list2)

83.1 µs ± 212 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [112]:
%%timeit -r 5 -n 10000
multiply_arrays(list1, list2)

708 ns ± 40 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


### BroadCasting

In [113]:
test_array = np.array([[1,2,3], [1,2,3], [1,2,3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [114]:
test_array[0,:] # first row

array([1, 2, 3])

In [115]:
test_array[:,1] # second column

array([2, 2, 2])

In [116]:
test_array[0,:] + test_array[:,1]

array([3, 4, 5])

In [117]:
test_array[0,:] + test_array[:,1].reshape(3,1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [118]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

## Filtering

## Array Manipulation