In [3]:
import numpy as np

### [Link to numpy basics types](https://numpy.org/devdocs/user/basics.types.html)

In [9]:
a1 = np.array(range(5))
a1

array([0, 1, 2, 3, 4])

### [Numpy Data types](https://numpy.org/devdocs/user/basics.types.html)

In [38]:
print("ndim        : ", a1.ndim)
print("shape       : ", a1.shape)
print("size        : ", a1.size)
print("dtype       : ", a1.dtype )
print("object Type : ", type(a1))

ndim        :  1
shape       :  (5,)
size        :  5
dtype       :  int64
object Type :  <class 'numpy.ndarray'>


In [39]:
print(a1)

[0 1 2 3 4]


In [25]:
np.exp(2)

7.38905609893065

In [26]:
2**2.71

6.543216468462249

In [27]:
2**2.71828

6.580877650466003

## Array Creation

#### ones
#### zeros
#### arange
#### linspace

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
start=0
end=20
step=2
np.arange(start, end, step)
# start inclusive end exclusive 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(1, 50, 5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [19]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
rng = np.random.default_rng(2310)
random_10 = rng.random(10)
np.sort(random_10)

array([0.04163222, 0.09369864, 0.10147996, 0.11112152, 0.38167364,
       0.63360001, 0.7019312 , 0.70479605, 0.73543922, 0.79266775])

In [39]:
rng.integers(1, 100, 10)

array([13, 36, 76, 78, 29, 95, 19, 73,  5,  3])

In [64]:
price_list = ( rng.random(10) * 10 ).round(2)
price_list

array([9.67, 1.7 , 1.12, 3.55, 5.42, 4.6 , 9.51, 2.58, 7.57, 3.7 ])

In [68]:
price_list[price_list > 5]

array([9.67, 5.42, 9.51, 7.57])

In [69]:
price_list[price_list < 5]

array([1.7 , 1.12, 3.55, 4.6 , 2.58, 3.7 ])

In [71]:
price_list

array([9.67, 1.7 , 1.12, 3.55, 5.42, 4.6 , 9.51, 2.58, 7.57, 3.7 ])

In [72]:
range_of_20 = np.arange(20)
range_of_20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
range_of_20 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [73]:
# range_of_20_even = 
range_of_20[range_of_20 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
np.where(range_of_20 % 2 == 0, "even", "odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

### Random sampling (numpy.random)

In [ ]:
rng = np.random.default_rng(1234)

In [ ]:
x1 = rng.integers(1,10,5)
np.sum(x1)

18

In [ ]:
rand_nums =  rng.random(10)
rand_nums

array([0.11809123, 0.24176629, 0.31853393, 0.96407925, 0.2636498 ,
       0.44100612, 0.60987081, 0.8636213 , 0.86375767, 0.67488131])

In [ ]:
rng.normal(5, 1, 10)
# normal(loc=0.0, scale=1.0, size=None)

array([5.5194932 , 3.73485628, 2.84086099, 5.43473395, 6.73328932,
       5.52013416, 3.99783421, 5.26834554, 5.7671747 , 6.19127203])

In [ ]:
x = rng.integers(1,10,5)
x

array([4, 5, 7, 6, 7])

### Structured arrays

In [28]:
data = np.array([('Alice', 25, 62.5, True),
                 ('Bob', 32, 70.2, False),
                 ('Charlie', 28, 68.7, True)],
                dtype=[('name', 'U10'), ('age', int), ('weight', float), ('is_student', bool)])
data

array([('Alice', 25, 62.5,  True), ('Bob', 32, 70.2, False),
       ('Charlie', 28, 68.7,  True)],
      dtype=[('name', '<U10'), ('age', '<i8'), ('weight', '<f8'), ('is_student', '?')])

#### Random Number Generator

In [29]:
rng = np.random.default_rng(123)

In [30]:
rng.random(10)

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [31]:
rng.integers(1, 10, size=5, endpoint=True )

array([1, 6, 3, 3, 3])

In [32]:
# normal (mean, std_dev, size)
rng.normal(2, 2, 10)

array([ 0.65782065,  4.00053884,  2.27264225,  5.06406616,  0.68006117,
        1.37641029,  2.67553825, -2.4149422 ,  3.65584288,  5.08326079])

In [33]:
rng.choice(np.arange(100), 5, replace=True)

array([82,  1, 58, 41, 18])

### Indexing & Slicing Arrays

In [35]:
countries = np.array([
    ['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
    ['France', 'Germany', 'Hungary', 'India', 'Japan'],
    ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
    ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
    ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']
])
countries

array([['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
       ['France', 'Germany', 'Hungary', 'India', 'Japan'],
       ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
       ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
       ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']], dtype='<U13')

In [36]:
countries[3,-1]

'United States'

In [37]:
countries[:, 3] # all rows - column 3

array(['Denmark', 'India', 'Oman', 'Thailand', 'Yemen'], dtype='<U13')

In [38]:
countries[:, 1:3] # all rows - second and third columns

array([['Brazil', 'Canada'],
       ['Germany', 'Hungary'],
       ['Mexico', 'Netherlands'],
       ['Russia', 'Spain'],
       ['Wales', 'Xenobia']], dtype='<U13')

In [39]:
countries[:2, 3:] # first 2 rows and columns 4 to the end

array([['Denmark', 'Egypt'],
       ['India', 'Japan']], dtype='<U13')

In [40]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
isEven= lambda x: x%2 == 0
isOdd = lambda n: n%2 != 0

In [42]:
result =[]
for x in range(n1.size):
    if isEven(x):
        result.append(x)

result

[0, 2, 4, 6, 8]

In [43]:
n1 = rng.integers(1, 100, 10)
n1

array([36,  2, 15, 47,  8, 73, 26, 91, 17, 62])

In [44]:
n1 > 50 # return numpy.ndarray

array([False, False, False, False, False,  True, False,  True, False,
        True])

In [45]:
n1 % 2 == 0

array([ True,  True, False, False,  True, False,  True, False, False,
        True])

In [46]:
mask_1 = np.in1d(n1, 83)
n1[mask_1]

array([], dtype=int64)

In [47]:
ar1 = np.arange(1, 21)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
ar1[ar1 %2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
even_odd = np.array(['even', 'odd'] * 5)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [50]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [51]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
np.where(ar1 %2==0, ar1/2, ar1/3)

array([ 0.33333333,  1.        ,  1.        ,  2.        ,  1.66666667,
        3.        ,  2.33333333,  4.        ,  3.        ,  5.        ,
        3.66666667,  6.        ,  4.33333333,  7.        ,  5.        ,
        8.        ,  5.66666667,  9.        ,  6.33333333, 10.        ])

In [53]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
ar2 = np.arange(19,-1, -1)
ar2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [55]:
ar1 + ar2

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20])

In [56]:
ar1.sort()

In [57]:
arr = np.array(['apple', 10, [1, 2, 3], {'key': 'value'}], dtype=object)

print(arr)
print(arr.dtype)

['apple' 10 list([1, 2, 3]) {'key': 'value'}]
object


In [81]:
unorder_arr = np.random.randint(1, 101, 10)
unorder_arr

array([89, 37,  8,  8, 29, 75, 46, 71, 80,  2])

In [82]:
unorder_arr.sort()
unorder_arr

array([ 2,  8,  8, 29, 37, 46, 71, 75, 80, 89])

In [83]:
desc_arr = np.flip(unorder_arr)
desc_arr

array([89, 80, 75, 71, 46, 37, 29,  8,  8,  2])

In [87]:
l1=[1,2,3,4,5]
l2=[6,7,8]

In [88]:
list(zip(l1,l2))

[(1, 6), (2, 7), (3, 8)]

### Vectorization

In [93]:
list1 = rng.integers(1, 1001, 1000)
list2 = rng.integers(1, 1001, 1000)

In [95]:
def for_loop_mutiply_arrays(array1, array2):
    product_array = []
    for n1, n2 in zip(array1, array2):
        product_array.append(n1 * n2)
    return product_array
        

In [96]:
def multiply_arrays(array1, array2):
    return array1 * array2

In [101]:
%%timeit -r 5 -n 10000
for_loop_mutiply_arrays(list1, list2)

83.9 µs ± 1.78 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [102]:
%%timeit -r 5 -n 10000
multiply_arrays(list1, list2)

728 ns ± 26.7 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


### BroadCasting

In [104]:
test_array = np.array([[1,2,3], [1,2,3], [1,2,3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [119]:
test_array[0,:] # first row

array([1, 2, 3])

In [120]:
test_array[:,1] # second column

array([2, 2, 2])

In [121]:
test_array[0,:] + test_array[:,1]

array([3, 4, 5])

In [117]:
test_array[0,:] + test_array[:,1].reshape(3,1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [118]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

## Filtering

In [14]:
a1.all() # false

False

In [16]:
# get index of not matching condition
falsy_values_at_index = a1[np.logical_not(a1)]
falsy_values_at_index

array([0])