In [18]:
import numpy as np

In [19]:
a1 = np.array(range(5))
a1

array([0, 1, 2, 3, 4])

In [20]:
print("ndim  : ", a1.ndim)
print("shape : ", a1.shape)
print("size  : ", a1.size)
print("dtype : ", a1.dtype )

ndim  :  1
shape :  (5,)
size  :  5
dtype :  int64


In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.exp(2)

7.38905609893065

In [26]:
2**2.71

6.543216468462249

In [27]:
2**2.71828

6.580877650466003

### Structured arrays

In [28]:
data = np.array([('Alice', 25, 62.5, True),
                 ('Bob', 32, 70.2, False),
                 ('Charlie', 28, 68.7, True)],
                dtype=[('name', 'U10'), ('age', int), ('weight', float), ('is_student', bool)])
data

array([('Alice', 25, 62.5,  True), ('Bob', 32, 70.2, False),
       ('Charlie', 28, 68.7,  True)],
      dtype=[('name', '<U10'), ('age', '<i8'), ('weight', '<f8'), ('is_student', '?')])

#### Random Number Generator

In [29]:
rng = np.random.default_rng(123)

In [30]:
rng.random(10)

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [31]:
rng.integers(1, 10, size=5, endpoint=True )

array([1, 6, 3, 3, 3])

In [32]:
# normal (mean, std_dev, size)
rng.normal(2, 2, 10)

array([ 0.65782065,  4.00053884,  2.27264225,  5.06406616,  0.68006117,
        1.37641029,  2.67553825, -2.4149422 ,  3.65584288,  5.08326079])

In [33]:
rng.choice(np.arange(100), 5, replace=True)

array([82,  1, 58, 41, 18])

### Indexing & Slicing Arrays

In [35]:
countries = np.array([
    ['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
    ['France', 'Germany', 'Hungary', 'India', 'Japan'],
    ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
    ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
    ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']
])
countries

array([['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
       ['France', 'Germany', 'Hungary', 'India', 'Japan'],
       ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
       ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
       ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']], dtype='<U13')

In [36]:
countries[3,-1]

'United States'

In [37]:
countries[:, 3] # all rows - column 3

array(['Denmark', 'India', 'Oman', 'Thailand', 'Yemen'], dtype='<U13')

In [38]:
countries[:, 1:3] # all rows - second and third columns

array([['Brazil', 'Canada'],
       ['Germany', 'Hungary'],
       ['Mexico', 'Netherlands'],
       ['Russia', 'Spain'],
       ['Wales', 'Xenobia']], dtype='<U13')

In [39]:
countries[:2, 3:] # first 2 rows and columns 4 to the end

array([['Denmark', 'Egypt'],
       ['India', 'Japan']], dtype='<U13')

In [40]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
isEven= lambda x: x%2 == 0
isOdd = lambda n: n%2 != 0

In [42]:
result =[]
for x in range(n1.size):
    if isEven(x):
        result.append(x)

result

[0, 2, 4, 6, 8]

In [43]:
n1 = rng.integers(1, 100, 10)
n1

array([36,  2, 15, 47,  8, 73, 26, 91, 17, 62])

In [44]:
n1 > 50 # return numpy.ndarray

array([False, False, False, False, False,  True, False,  True, False,
        True])

In [45]:
n1 % 2 == 0

array([ True,  True, False, False,  True, False,  True, False, False,
        True])

In [46]:
mask_1 = np.in1d(n1, 83)
n1[mask_1]

array([], dtype=int64)

In [47]:
ar1 = np.arange(1, 21)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
ar1[ar1 %2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
even_odd = np.array(['even', 'odd'] * 5)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [50]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [51]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
np.where(ar1 %2==0, ar1/2, ar1/3)

array([ 0.33333333,  1.        ,  1.        ,  2.        ,  1.66666667,
        3.        ,  2.33333333,  4.        ,  3.        ,  5.        ,
        3.66666667,  6.        ,  4.33333333,  7.        ,  5.        ,
        8.        ,  5.66666667,  9.        ,  6.33333333, 10.        ])

In [53]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
ar2 = np.arange(19,-1, -1)
ar2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [55]:
ar1 + ar2

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20])

In [56]:
ar1.sort()

In [57]:
arr = np.array(['apple', 10, [1, 2, 3], {'key': 'value'}], dtype=object)

print(arr)
print(arr.dtype)

['apple' 10 list([1, 2, 3]) {'key': 'value'}]
object


In [81]:
unorder_arr = np.random.randint(1, 101, 10)
unorder_arr

array([89, 37,  8,  8, 29, 75, 46, 71, 80,  2])

In [82]:
unorder_arr.sort()
unorder_arr

array([ 2,  8,  8, 29, 37, 46, 71, 75, 80, 89])

In [83]:
desc_arr = np.flip(unorder_arr)
desc_arr

array([89, 80, 75, 71, 46, 37, 29,  8,  8,  2])

In [87]:
l1=[1,2,3,4,5]
l2=[6,7,8]

In [88]:
list(zip(l1,l2))

[(1, 6), (2, 7), (3, 8)]

### Vectorization

In [93]:
list1 = rng.integers(1, 1001, 1000)
list2 = rng.integers(1, 1001, 1000)

In [95]:
def for_loop_mutiply_arrays(array1, array2):
    product_array = []
    for n1, n2 in zip(array1, array2):
        product_array.append(n1 * n2)
    return product_array
        

In [96]:
def multiply_arrays(array1, array2):
    return array1 * array2

In [101]:
%%timeit -r 5 -n 10000
for_loop_mutiply_arrays(list1, list2)

83.9 µs ± 1.78 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [102]:
%%timeit -r 5 -n 10000
multiply_arrays(list1, list2)

728 ns ± 26.7 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


### BroadCasting

In [104]:
test_array = np.array([[1,2,3], [1,2,3], [1,2,3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [105]:
test_array[0,:]

array([1, 2, 3])

In [111]:
test_array[:,1]

array([2, 2, 2])

In [112]:
test_array[:,1].reshape(3,1)

array([[2],
       [2],
       [2]])

In [109]:
test_array[0,:] + test_array[:,1]

array([3, 4, 5])