In [16]:
import numpy as np

In [17]:
a1 = np.array(range(5))
a1

array([0, 1, 2, 3, 4])

In [18]:
print("ndim  : ", a1.ndim)
print("shape : ", a1.shape)
print("size  : ", a1.size)
print("dtype : ", a1.dtype )

ndim  :  1
shape :  (5,)
size  :  5
dtype :  int64


In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.exp(2)

7.38905609893065

In [24]:
2**2.71

6.543216468462249

In [25]:
2**2.71828

6.580877650466003

#### Random Number Generator

In [85]:
rng = np.random.default_rng(123)

In [87]:
rng.random(10)

array([0.51297046, 0.2449646 , 0.8242416 , 0.21376296, 0.74146705,
       0.6299402 , 0.92740726, 0.23190819, 0.79912513, 0.51816504])

In [96]:
rng.integers(1, 10, size=5, endpoint=True )

array([1, 4, 5, 7, 5])

In [88]:
# normal (mean, std_dev, size)
rng.normal(2, 2, 10)

array([-2.4149422 ,  3.65584288,  5.08326079,  4.25361359,  3.50953929,
        1.70804421,  4.56380445,  4.14806124,  2.78524169,  2.01022863])

In [89]:
rng.choice(np.arange(100), 5, replace=True)

array([51, 91, 61, 86, 46])

### Indexing & Slicing Arrays

In [103]:
country = np.array([
    ['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
    ['France', 'Germany', 'Hungary', 'India', 'Japan'],
    ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
    ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
    ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']
])
country

array([['Argentina', 'Brazil', 'Canada', 'Denmark', 'Egypt'],
       ['France', 'Germany', 'Hungary', 'India', 'Japan'],
       ['Kenya', 'Mexico', 'Netherlands', 'Oman', 'Poland'],
       ['Qatar', 'Russia', 'Spain', 'Thailand', 'United States'],
       ['Vietnam', 'Wales', 'Xenobia', 'Yemen', 'Zimbabwe']], dtype='<U13')

In [104]:
country[:, 2:4]

array([['Canada', 'Denmark'],
       ['Hungary', 'India'],
       ['Netherlands', 'Oman'],
       ['Spain', 'Thailand'],
       ['Xenobia', 'Yemen']], dtype='<U13')