In [1]:
import numpy as np

In [2]:
array_info = lambda x: print(f"Shape {x.shape} | dimension {x.ndim} | size {x.size} | dtype {x.dtype}")


In [25]:
a=np.arange(10)

In [28]:
next(i[0] for i, v in np.ndenumerate(a) if v==8)

8

In [29]:
l1=list(range(10))

In [32]:
next(i for i in iter(l1) if i>3)

4

#### Creating array

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [7]:
array_info(c)

Shape (2, 2, 3) | dimension 3 | size 12 | dtype float64


##### Create an array of zeros

In [8]:
np.zeros((3,), dtype = np.int16, order = 'C')

array([0, 0, 0], dtype=int16)

##### Create an array of ones

In [9]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

##### Create an array of evenly spaced values 


In [10]:
np.arange(start=0, stop=30, step=2, dtype = np.float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28.])

### LinSpace
>##### Create an array of evenly spaced values

In [11]:
np.linspace(start=1, stop= 11, num=10, endpoint=False)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
arr2d1 = np.linspace([1,2],[5,6],5)
arr2d1

array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [4., 5.],
       [5., 6.]])

### LinSpace 
>##### with axis Argument
>Using the axis argument, we can specify in which axis to store these 1D arrays. It’s 0 by default, which means the 1D arrays are added as columns to the 2D array. If the axis is set to 1, then the 1D arrays are added as rows

In [13]:
arr2d2 = np.linspace(start=range(1,6), stop = 10, num=10, endpoint=True)

In [14]:
arr2d2

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556],
       [ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111],
       [ 4.        ,  4.66666667,  5.33333333,  6.        ,  6.66666667],
       [ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222],
       [ 6.        ,  6.44444444,  6.88888889,  7.33333333,  7.77777778],
       [ 7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333],
       [ 8.        ,  8.22222222,  8.44444444,  8.66666667,  8.88888889],
       [ 9.        ,  9.11111111,  9.22222222,  9.33333333,  9.44444444],
       [10.        , 10.        , 10.        , 10.        , 10.        ]])

In [15]:
array_info(arr2d2)

Shape (10, 5) | dimension 2 | size 50 | dtype float64


In [16]:
a1d2=np.array([2,2,2])

In [17]:
a2d1=np.array([[1,1,1],[2,2,2]])

In [18]:
a2d2=np.array([[3,3,3],[4,4,4]])

In [19]:
a3d1=np.array([[[1,1,1],[2,2,2],[3,3,3]]])

In [20]:
a3d2=np.array([[[4,4,4],[5,5,5],[6,6,6]]])

In [21]:
a2d1, a2d2

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([[3, 3, 3],
        [4, 4, 4]]))

In [22]:
# numpy.ndarray.view

#da vedere

## numpy.empty
create an empty array with junk values

In [33]:
x=np.empty((2,2))
x

array([[2.00000000e+000, 3.11109885e+231],
       [2.32036353e+077, 2.78134232e-309]])

## numpy.delete

In [34]:
d1=np.array([0,1,2,3,4,5,6,7,8,9])
d2=np.array(range(9)).reshape(3,3)
d3=np.array(range(18)).reshape(2,3,3)

In [41]:
np.delete(d1,[0,1,2])

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
d2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.delete(d2, 8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.delete(d2, 0,1)


array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
np.delete(d2, 1,0)

array([[0, 1, 2],
       [6, 7, 8]])

In [63]:
d3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [64]:
d3.ndim, d3.shape

(3, (2, 3, 3))

In [65]:
d3[0,0,2]

2

In [72]:
np.delete(d3, 2, axis=1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [ ]:
x1

## CONCATENATE

In [75]:
a2d1

array([[1, 1, 1],
       [2, 2, 2]])

In [76]:
a2d2

array([[3, 3, 3],
       [4, 4, 4]])

In [77]:
np.concatenate((a2d1, a2d2))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [78]:
np.concatenate((a2d1, a2d2), axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [79]:
np.concatenate((a2d1, a2d2), axis=1)

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

In [80]:
a3d1, a3d2

(array([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]),
 array([[[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]]))

In [81]:
np.concatenate((a3d1, a3d2), axis=2)

array([[[1, 1, 1, 4, 4, 4],
        [2, 2, 2, 5, 5, 5],
        [3, 3, 3, 6, 6, 6]]])

## APPEND

In [82]:
np.append(a2d1, a2d2)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [83]:
np.append(a2d1, a2d2, axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [84]:
np.append(a2d1, a2d2, axis=1)

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

In [85]:
a3d1, a3d2

(array([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]),
 array([[[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]]))

In [86]:
np.append(a3d1, a3d2, axis=2)

array([[[1, 1, 1, 4, 4, 4],
        [2, 2, 2, 5, 5, 5],
        [3, 3, 3, 6, 6, 6]]])

https://stackoverflow.com/questions/16473042/numpy-vstack-vs-column-stack

## STACK

##  HSTACK

In [ ]:
np.hstack((a1d1, a1d2))

In [ ]:
a2d1, a2d2

In [ ]:
np.hstack((a2d1,a2d2))

In [ ]:
a3d1, a3d2

In [ ]:
a3d1.shape, a3d1.size, a3d1.ndim

In [ ]:
np.hstack((a3d1,a3d2))

##  VSTACK

In [ ]:
np.vstack((a1d1, a1d2))

In [ ]:
np.vstack((a2d1, a2d2))

In [ ]:
np.vstack((a3d1, a3d2))

In [ ]:
a2d1

In [ ]:
np.append(a2d1,[[2,3],[3,4]])

## numpy.insert

In [ ]:
a1d1

In [ ]:
np.insert(a1d1, 0, (2,2,2))

In [ ]:
a2d1

In [ ]:
np.insert(a2d1, 0, (3,3,3))

In [ ]:
a3d1

In [ ]:
np.insert(a3d1, 1,[4,4,4],axis=1)

## SPLIT

## RAVEL

## FLIPLR

##  FLIPUD

## ROLL

## ROT90

## TRANSPOSE-LIKE OPERATIONS

#### NP.TRANSPOSE

#### NP.SWAPAXES

#### NP.ROLLAXIS

## TILING ARRAYS
#### numpy.tile

#### numpy.repeat