In [1]:
import numpy as np

In [5]:
a1_20 = np.array(range(1,21))
print("a1_20 : ", a1_20)

a1_20 :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [26]:
a1_20_mask_even = 0 == (a1_20 % 2) # create mask
print("a1_20_mask_even\n", a1_20_mask_even)

a1_20_mask_even
 [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]


In [7]:
a1_20_mask_greater10 = a1_20 > 10
print("a1_20_mask_greater10\n", a1_20_mask_greater10)


a1_20_mask_greater10
 [False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]


In [8]:
a1_20_even_greater10_mask1=(a1_20 %2 == 0) & (a1_20 > 10) # create mask with 2 conditions
print("a1_20_even_greater10_mask1\n", a1_20_even_greater10_mask1)
print(a1_20[a1_20_even_greater10_mask1])

a1_20_even_greater10_mask1
 [False False False False False False False False False False False  True
 False  True False  True False  True False  True]
[12 14 16 18 20]


In [9]:
a1_20_even_greater10_mask2 = np.logical_and(a1_20_mask_even, a1_20_mask_greater10)
print("a1_20_even_greater10_mask2\n", a1_20_even_greater10_mask2)
print(a1_20[a1_20_even_greater10_mask2])

a1_20_even_greater10_mask2
 [False False False False False False False False False False False  True
 False  True False  True False  True False  True]
[12 14 16 18 20]


In [10]:
a1_20_even_greater10_mask3 = np.logical_and((a1_20 %2 == 0), (a1_20 > 10))
print("a1_20_even_greater10_mask3\n", a1_20_even_greater10_mask3)
print(a1_20[a1_20_even_greater10_mask3])


a1_20_even_greater10_mask3
 [False False False False False False False False False False False  True
 False  True False  True False  True False  True]
[12 14 16 18 20]


In [11]:
a1_20_even = a1_20[a1_20_mask_even] # create array from mask
print("nuova array applicando il primo mask\n", a1_20_even)

nuova array applicando il primo mask
 [ 2  4  6  8 10 12 14 16 18 20]


In [12]:
a1_20_even_greater10_1 = a1_20_even[a1_20_even > 10] # create array from array with it's condition
print("nuova array applicando il secondo mask\n", a1_20_even_greater10_1)


nuova array applicando il secondo mask
 [12 14 16 18 20]


In [13]:
a1_20_even_and_greater10 = a1_20[a1_20_even_greater10_mask3]
print("array finale con 2 masks applicate\n", a1_20_even_and_greater10)

array finale con 2 masks applicate
 [12 14 16 18 20]


In [15]:
a1_20 = np.array(range(1,21))
a1_20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a1_20_mask1_even = 0 ==  a1_20 % 2
a1_20_mask1_even

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [17]:
a1_20_mask2_greater10 = a1_20 > 10
a1_20_mask2_greater10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
a1_20_mask1_mask2_operator = (a1_20 %2 == 0) & (a1_20>10)
a1_20_mask1_mask2_operator

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [19]:
a1_20 [a1_20_mask1_mask2_operator]

array([12, 14, 16, 18, 20])

In [20]:
a1_20_mask1_mask2_np_logical_and1 = np.logical_and((a1_20_mask1_even),(a1_20_mask2_greater10))

In [21]:
a1_20[a1_20_mask1_mask2_np_logical_and1]

array([12, 14, 16, 18, 20])

In [22]:
a1_20_mask1_mask2_np_logical_and2 = np.logical_and((a1_20 %2 == 0), (a1_20 > 10))

In [23]:
a1_20[a1_20_mask1_mask2_np_logical_and2]

array([12, 14, 16, 18, 20])

In [24]:
a1_20[a1_20>14]

array([15, 16, 17, 18, 19, 20])

In [25]:
a1_20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])