In [1]:
import numpy as np

In [2]:
from sympy import *
init_printing()

### [Link to numpy basics types](https://numpy.org/devdocs/user/basics.types.html)

In [3]:
np.array([1,2,3,4],dtype=np.long) # dfine np.array from list as object

array([1, 2, 3, 4])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3,3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
np.empty(10)

array([-2.31584178e+077,  1.29073982e-231,  2.35541533e-312,
        6.79038654e-313,  2.22809558e-312,  2.14321575e-312,
        2.46151512e-312,  2.41907520e-312,  5.97819431e-322,
        7.64702964e-309])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.linspace(1, 12, num=3)

array([ 1. ,  6.5, 12. ])

In [78]:
x=np.array(range(36,0, -1)).reshape(3,4,3)
x

array([[[36, 35, 34],
        [33, 32, 31],
        [30, 29, 28],
        [27, 26, 25]],

       [[24, 23, 22],
        [21, 20, 19],
        [18, 17, 16],
        [15, 14, 13]],

       [[12, 11, 10],
        [ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [79]:
(x.shape)[0]

In [80]:
for x in np.nditer(x, order='C'):
    print(x," ")

36  
35  
34  
33  
32  
31  
30  
29  
28  
27  
26  
25  
24  
23  
22  
21  
20  
19  
18  
17  
16  
15  
14  
13  
12  
11  
10  
9  
8  
7  
6  
5  
4  
3  
2  
1  


In [81]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b=np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [17]:
print(a.ndim, a.size, a.shape)

2 6 (2, 3)


In [18]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [19]:
a2 = a[np.newaxis, :]

In [20]:
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
a2.shape

In [22]:
b=np.expand_dims(a, axis=0)

In [23]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [24]:
b.shape

In [25]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1[(a1<9)]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a1[ (a1>2) & (a1<9) ]

array([3, 4, 5, 6, 7, 8])

In [27]:
a2=np.array(range(10), dtype=int)

In [28]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a=np.array([x for x in range(20) if x %2 == 0])
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
a * 2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [32]:
na3=np.linspace(1,3,4)
na3

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [17]:
na4=np.linspace(1,20,10, retstep=False)
na4

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [34]:
na5=np.arange(1,11,3)
na5

array([ 1,  4,  7, 10])

In [35]:
na6=np.arange(20)
na6.shape=(4,5)

na6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
na7=np.arange(45)
na7.shape=(3,3,5)
na7

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

## combinazione list comprehebsion all'interno di np.array( )

In [8]:
np.array([range(i, i+4) for i in [1,2,3,4]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [10]:
np.array([range(i, i + 5) for i in range(1,6)])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [39]:
#-----------------------------------
np.full((2,2),0)

array([[0, 0],
       [0, 0]])

In [40]:
var('x,y,n')

In [41]:
# formula (start X, stop Y, step N) = (Y - X) / N -1
np.linspace(0,1,5)
# 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
np.random.random((2,5),)+1

array([[1.89667427, 1.85023992, 1.73878486, 1.19373777, 1.28342862],
       [1.40145077, 1.22366938, 1.75687782, 1.28811545, 1.44803693]])

In [43]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])

In [44]:
x.dtype

dtype([('a', 'i1'), ('b', 'i1')])

## Array - Adding and Removing

In [45]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
b=np.append(a,range(4)).reshape(7,4)

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3]])

In [48]:
c=np.array(range(24)).reshape(2,3,4) * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [49]:
print(a.shape, a.size)
a,c

(2, 3, 4) 24


(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[  3,  13,  23,  33],
         [ 43,  53,  63,  73],
         [ 83,  93, 103, 113]],
 
        [[123, 133, 143, 153],
         [163, 173, 183, 193],
         [203, 213, 223, 233]]]))

In [50]:
np.append(a,c, axis = 0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])