In [1]:
import numpy as np

In [5]:
np.random.seed(31)
np.random.randint(1, 100)

83

In [26]:
# array_info = lambda x: print(f"Shape {x.shape} | dimension {x.ndim} | size {x.size} | dtype {x.dtype}")
def array_info(array: np.ndarray):
    print(f"Shape {array.shape} | dimension {array.ndim} | size {array.size} | dtype {array.dtype}")

In [35]:
a=np.arange(10)

In [74]:
next(i[0] for i, v in np.ndenumerate(a) if v==8)

8

In [94]:
l1=list(range(10))

In [95]:
next(i for i in iter(l1) if i>3)

4

In [99]:
next(i for i in iter(l1) if i < len(l1))

0

#### Creating array

In [25]:
a = np.array([1,2,3])
a

In [26]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

In [27]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
c

In [29]:
array_info(c)

##### Create an array of zeros

In [30]:
np.zeros((3,), dtype = np.int16, order = 'C')

##### Create an array of ones

In [31]:
np.ones((2,3,4), dtype = np.int16)

##### Create an array of evenly spaced values 


In [10]:
np.arange(start=0, stop=30, step=2, dtype=np.int16)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
      dtype=int16)

### LinSpace
>##### Create an array of evenly spaced values

In [11]:
np.linspace(start=1, stop= 11, num=10, endpoint=False)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace([1,2,3], [8,9,10], 5)

array([[ 1.  ,  2.  ,  3.  ],
       [ 2.75,  3.75,  4.75],
       [ 4.5 ,  5.5 ,  6.5 ],
       [ 6.25,  7.25,  8.25],
       [ 8.  ,  9.  , 10.  ]])

In [12]:
arr2d1 = np.linspace([1,2],[5,6],5)
arr2d1

array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [4., 5.],
       [5., 6.]])

### LinSpace 
>##### with axis Argument
>Using the axis argument, we can specify in which axis to store these 1D arrays. It’s 0 by default, which means the 1D arrays are added as columns to the 2D array. If the axis is set to 1, then the 1D arrays are added as rows

In [ ]:
arr2d2 = np.linspace(start=range(1,6), stop = 10, num=10, endpoint=True)

In [ ]:
arr2d2

In [ ]:
array_info(arr2d2)

In [ ]:
a1d2=np.array([2,2,2])

In [ ]:
a2d1=np.array([[1,1,1],[2,2,2]])

In [ ]:
a2d2=np.array([[3,3,3],[4,4,4]])

In [ ]:
a3d1=np.array([[[1,1,1],[2,2,2],[3,3,3]]])

In [ ]:
a3d2=np.array([[[4,4,4],[5,5,5],[6,6,6]]])

In [ ]:
a2d1, a2d2

In [ ]:
# numpy.ndarray.view

#da vedere

## numpy.empty
create an empty array with junk values

In [20]:
np.empty((2,2))

array([[0., 1.],
       [2., 3.]])

In [ ]:
x=np.empty((2,2))
x

## numpy.delete

In [ ]:
d1=np.array([0,1,2,3,4,5,6,7,8,9])
d2=np.array(range(9)).reshape(3,3)
d3=np.array(range(18)).reshape(2,3,3)

In [ ]:
np.delete(d1,[0,1,2])

In [ ]:
d2

In [ ]:
np.delete(d2, 8)

In [ ]:
np.delete(d2, 0,1)


In [ ]:
np.delete(d2, 1,0)

In [ ]:
d3

In [ ]:
d3.ndim, d3.shape

In [ ]:
d3[0,0,2]

In [ ]:
np.delete(d3, 2, axis=1)

In [ ]:
x1

## CONCATENATE

In [ ]:
a2d1

In [ ]:
a2d2

In [ ]:
np.concatenate((a2d1, a2d2))

In [ ]:
np.concatenate((a2d1, a2d2), axis=0)

In [ ]:
np.concatenate((a2d1, a2d2), axis=1)

In [ ]:
a3d1, a3d2

In [ ]:
np.concatenate((a3d1, a3d2), axis=2)

## APPEND

In [ ]:
np.append(a2d1, a2d2)

In [ ]:
np.append(a2d1, a2d2, axis=0)

In [ ]:
np.append(a2d1, a2d2, axis=1)

In [ ]:
a3d1, a3d2

In [ ]:
np.append(a3d1, a3d2, axis=2)

https://stackoverflow.com/questions/16473042/numpy-vstack-vs-column-stack

## STACK

##  HSTACK

In [ ]:
np.hstack((a1d1, a1d2))

In [ ]:
a2d1, a2d2

In [ ]:
np.hstack((a2d1,a2d2))

In [ ]:
a3d1, a3d2

In [ ]:
a3d1.shape, a3d1.size, a3d1.ndim

In [ ]:
np.hstack((a3d1,a3d2))

##  VSTACK

In [ ]:
np.vstack((a1d1, a1d2))

In [ ]:
np.vstack((a2d1, a2d2))

In [ ]:
np.vstack((a3d1, a3d2))

In [ ]:
a2d1

In [ ]:
np.append(a2d1,[[2,3],[3,4]])

## numpy.insert

In [ ]:
a1d1

In [ ]:
np.insert(a1d1, 0, (2,2,2))

In [ ]:
a2d1

In [ ]:
np.insert(a2d1, 0, (3,3,3))

In [ ]:
a3d1

In [ ]:
np.insert(a3d1, 1,[4,4,4],axis=1)

## SPLIT

## RAVEL

## FLIPLR

##  FLIPUD

## ROLL

## ROT90

## TRANSPOSE-LIKE OPERATIONS

#### NP.TRANSPOSE

#### NP.SWAPAXES

#### NP.ROLLAXIS

## TILING ARRAYS
#### numpy.tile

#### numpy.repeat