In [1]:
import numpy as np

In [2]:
arr1d = np.array([x for x in range(10)])

In [3]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1d.ndim

1

In [5]:
arr1d.shape

(10,)

In [6]:
arr1d.size

10

In [7]:
arr1d.dtype

dtype('int64')

In [8]:
arr2d =  np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
arr2d.ndim

2

In [10]:
arr2d.shape

(2, 5)

In [11]:
arr2d.size

10

In [12]:
arr2d.dtype

dtype('int64')

In [13]:
arr2d.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [14]:
arr2d.T.shape

(5, 2)

## Array Creation

#### ones
#### zeros
#### arange
#### linspace

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(1, 50, 5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [19]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
rng = np.random.default_rng(2310)
random_10 = rng.random(10)
np.sort(random_10)

array([0.04163222, 0.09369864, 0.10147996, 0.11112152, 0.38167364,
       0.63360001, 0.7019312 , 0.70479605, 0.73543922, 0.79266775])

In [39]:
rng.integers(1, 100, 10)

array([13, 36, 76, 78, 29, 95, 19, 73,  5,  3])

In [64]:
price_list = ( rng.random(10) * 10 ).round(2)
price_list

array([9.67, 1.7 , 1.12, 3.55, 5.42, 4.6 , 9.51, 2.58, 7.57, 3.7 ])

In [68]:
price_list[price_list > 5]

array([9.67, 5.42, 9.51, 7.57])

In [69]:
price_list[price_list < 5]

array([1.7 , 1.12, 3.55, 4.6 , 2.58, 3.7 ])

In [71]:
price_list

array([9.67, 1.7 , 1.12, 3.55, 5.42, 4.6 , 9.51, 2.58, 7.57, 3.7 ])

In [72]:
range_of_20 = np.arange(20)
range_of_20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
range_of_20 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [73]:
# range_of_20_even = 
range_of_20[range_of_20 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
np.where(range_of_20 % 2 == 0, "even", "odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')